"""
FastAPI wrapper for validation-check
Auto-generated by KRE Agent Builder — provides /chat, /health, /run, /info, /status, /upload endpoints.
"""
import os
import json
import logging
import sys
import time
import traceback
import threading
import hashlib
import importlib.util
import uvicorn
from fastapi import FastAPI, HTTPException, UploadFile, File
from pydantic import BaseModel
from typing import Any, Dict, List, Optional

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(name)s: %(message)s")
logger = logging.getLogger("validation-check")

app = FastAPI(title="validation-check", version="1.0.0")

from fastapi.middleware.cors import CORSMiddleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── Load agent module with full error visibility ──────────────────────────────
_agent_instance = None
_agent_loading = True          # True while background loading is in progress
_agent_load_error = None       # Stores error string if loading fails
# Use AGENT_SYSTEM_PROMPT env var injected at deploy time so the fallback LLM
# response uses the correct persona instead of a bare "helpful assistant".
_agent_sys_prompt = os.environ.get(
    "AGENT_SYSTEM_PROMPT",
    "You are a helpful AI assistant called validation-check.",
)
_agent_module_path = 'agent_module.py'


def _load_agent() -> None:
    """Load agent module — designed to run in a background thread so the web
    server can start immediately and respond to /health startup probes."""
    global _agent_instance, _agent_sys_prompt, _agent_loading, _agent_load_error
    _load_start = time.monotonic()
    try:
        project_root = os.path.dirname(os.path.abspath(__file__))
        if project_root not in sys.path:
            sys.path.insert(0, project_root)
        module_path = os.path.join(project_root, _agent_module_path.replace("/", os.sep))
        if not os.path.exists(module_path):
            _agent_load_error = f"Agent module not found: {_agent_module_path}"
            logger.error("CRITICAL: %s not found at %s", _agent_module_path, module_path)
            return
        try:
            spec = importlib.util.spec_from_file_location("agent_module", module_path)
            mod = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(mod)  # type: ignore[union-attr]
            logger.info("%s loaded successfully (%.1fs)", _agent_module_path, time.monotonic() - _load_start)
        except Exception as exc:
            _agent_load_error = f"Module import failed: {exc}"
            logger.error(
                "CRITICAL: %s failed to load - %s\n%s",
                _agent_module_path,
                exc,
                traceback.format_exc(),
            )
            return

        # Discover agent class: prefer "Agent", then any class defined in this module
        preferred_names = {"Agent", "Bot", "Assistant"}
        candidates: List[tuple] = []
        for name in preferred_names:
            cls = getattr(mod, name, None)
            if cls is not None and isinstance(cls, type):
                candidates.insert(0, (name, cls))
        for name in dir(mod):
            if name.startswith("_"):
                continue
            cls = getattr(mod, name, None)
            if cls is None or not isinstance(cls, type):
                continue
            if getattr(cls, "__module__", None) not in ("agent_module", None):
                continue
            if any(c[0] == name for c in candidates):
                continue
            candidates.append((name, cls))

        for cls_name, cls in candidates:
            try:
                instance = cls()
                _agent_instance = instance
                # Extract system_prompt from the instance if available
                for attr in ("system_prompt", "_system_prompt"):
                    val = getattr(instance, attr, None)
                    if val and isinstance(val, str):
                        _agent_sys_prompt = val
                        break
                cfg = getattr(instance, "config", None)
                if cfg and isinstance(cfg, dict):
                    sp = cfg.get("system_prompt")
                    if sp:
                        _agent_sys_prompt = sp
                logger.info("Agent class '%s' instantiated successfully (%.1fs total)", cls_name, time.monotonic() - _load_start)
                return
            except Exception as exc:
                logger.warning("Could not instantiate '%s': %s", cls_name, exc)

        _agent_load_error = "No agent class could be instantiated"
        logger.error("No agent class could be instantiated from %s", _agent_module_path)
    finally:
        _agent_loading = False
        logger.info("Agent loading completed in %.1fs (loaded=%s)", time.monotonic() - _load_start, _agent_instance is not None)
        # Initialize RAG store AFTER agent loading (still in background thread)
        _init_rag_store()


# Start loading in a background thread so the web server boots immediately
# and /health can respond to Cloud Run startup probes right away.
_loader_thread = threading.Thread(target=_load_agent, daemon=True, name="agent-loader")
_loader_thread.start()


# ── In-container RAG store (ChromaDB) ──────────────────────────────────────────
# Self-contained RAG: uploaded files are chunked, embedded, and stored locally.
# The /chat endpoint retrieves relevant chunks and injects them as LLM context.
_rag_collection = None
_rag_ready = False

def _init_rag_store():
    """Initialize ChromaDB collection for in-container RAG."""
    global _rag_collection, _rag_ready
    try:
        import chromadb
        client = chromadb.Client()  # ephemeral in-memory store
        _rag_collection = client.get_or_create_collection(
            name="agent_knowledge",
            metadata={"hnsw:space": "cosine"},
        )
        _rag_ready = True
        logger.info("ChromaDB RAG store initialized (in-memory)")
    except ImportError:
        logger.warning("chromadb not installed — RAG disabled. Add 'chromadb' to requirements.txt.")
    except Exception as e:
        logger.warning("ChromaDB init failed (non-fatal): %s", e)

# NOTE: _init_rag_store() is called inside the background loader thread,
# NOT at module top-level — prevents import-time crashes from blocking uvicorn.


def _chunk_text(text: str, chunk_size: int = 500, overlap: int = 50) -> List[str]:
    """Split text into overlapping chunks for RAG ingestion."""
    chunks = []
    start = 0
    text = text.strip()
    while start < len(text):
        end = start + chunk_size
        chunk = text[start:end].strip()
        if chunk:
            chunks.append(chunk)
        start += chunk_size - overlap
    return chunks


def _extract_text_from_file(file_bytes: bytes, filename: str) -> str:
    """Extract plain text from uploaded file (PDF, TXT, etc.)."""
    ext = filename.rsplit(".", 1)[-1].lower() if "." in filename else ""
    if ext == "pdf":
        try:
            import pdfplumber
            import io
            with pdfplumber.open(io.BytesIO(file_bytes)) as pdf:
                pages = [page.extract_text() or "" for page in pdf.pages]
            return "\n\n".join(p.strip() for p in pages if p.strip())
        except ImportError:
            logger.warning("pdfplumber not installed — cannot parse PDF")
            return ""
        except Exception as e:
            logger.warning("PDF extraction failed: %s", e)
            return ""
    # Plain text files
    try:
        return file_bytes.decode("utf-8", errors="replace")
    except Exception:
        return ""


def _ingest_to_rag(text: str, source: str = "upload") -> int:
    """Chunk text and add to ChromaDB collection. Returns number of chunks added."""
    if not _rag_ready or not _rag_collection:
        return 0
    chunks = _chunk_text(text)
    if not chunks:
        return 0
    ids = [hashlib.md5(f"{source}:{i}:{c[:50]}".encode()).hexdigest() for i, c in enumerate(chunks)]
    metadatas = [{"source": source, "chunk_index": i} for i in range(len(chunks))]
    _rag_collection.upsert(documents=chunks, ids=ids, metadatas=metadatas)
    logger.info("Ingested %d chunks from %s into ChromaDB", len(chunks), source)
    return len(chunks)


def _query_rag(query: str, top_k: int = 5) -> str:
    """Query ChromaDB for relevant chunks and return formatted context."""
    if not _rag_ready or not _rag_collection:
        return ""
    try:
        count = _rag_collection.count()
        if count == 0:
            return ""
        results = _rag_collection.query(
            query_texts=[query],
            n_results=min(top_k, count),
        )
        docs = results.get("documents", [[]])[0]
        if not docs:
            return ""
        context_parts = []
        for i, doc in enumerate(docs, 1):
            context_parts.append(f"[{i}] {doc}")
        return (
            "\n\n=== KNOWLEDGE BASE CONTEXT ===\n"
            "The following information was retrieved from the uploaded documents. "
            "Use this context to answer the user's question accurately.\n\n"
            + "\n\n---\n\n".join(context_parts)
            + "\n=== END OF KNOWLEDGE BASE CONTEXT ===\n"
        )
    except Exception as e:
        logger.warning("RAG query failed: %s", e)
        return ""


# ── Real LLM fallback via Vertex AI / Gemini ──────────────────────────────────
def _call_gemini_fallback(message: str) -> str:
    """Call Gemini when the agent module is unavailable or returns nothing useful."""
    prompt = f"{_agent_sys_prompt}\n\nUser: {message}"
    _vertex_error = None  # Persist across except blocks (Python 3 deletes exception vars)

    # 1. Try Vertex AI (uses ADC — always available in Cloud Run)
    try:
        import vertexai
        from vertexai.generative_models import GenerativeModel
        project = (
            os.environ.get("GOOGLE_CLOUD_PROJECT")
            or os.environ.get("PROJECT_ID", "gen-ai-poc-onboarding")
        )
        location = os.environ.get("GOOGLE_CLOUD_REGION", "us-central1")
        vertexai.init(project=project, location=location)
        model = GenerativeModel("gemini-2.5-flash")
        response = model.generate_content(prompt)
        return response.text
    except Exception as vertex_err:
        _vertex_error = vertex_err
        logger.warning("Vertex AI fallback failed: %s", vertex_err)

    # 2. Try google.generativeai with API key
    try:
        import google.generativeai as genai  # type: ignore
        api_key = os.environ.get("GOOGLE_API_KEY") or os.environ.get("GEMINI_API_KEY")
        if not api_key:
            raise ValueError("GOOGLE_API_KEY / GEMINI_API_KEY not set")
        genai.configure(api_key=api_key)
        model = genai.GenerativeModel("gemini-2.5-flash")
        response = model.generate_content(prompt)
        return response.text
    except Exception as genai_err:
        logger.error("All LLM fallbacks exhausted — Vertex: %s | Gemini: %s", _vertex_error, genai_err)
        return f"Hello! I am validation-check. I received your message but my AI backend is not reachable right now."


# ── KRE backend proxy ──────────────────────────────────────────────
# When KRE_BACKEND_URL + KRE_AGENT_ID env vars are set (injected at deploy time),
# /chat proxies to the KRE platform backend which has full context:
#   - Firestore agent config (system prompt, training history)
#   - ChromaDB RAG knowledge base
#   - MCP server credentials + function-calling
_KRE_BACKEND_URL = os.environ.get("KRE_BACKEND_URL", "").rstrip("/")
_KRE_AGENT_ID    = os.environ.get("KRE_AGENT_ID", "")


def _call_kre_backend(message: str) -> Optional[str]:
    """Proxy the chat message to the KRE backend (full context: Firestore/RAG/MCP)."""
    if not (_KRE_BACKEND_URL and _KRE_AGENT_ID):
        return None
    # Use /api/proxy/agent-chat (no Firebase auth needed — same endpoint the sandbox uses)
    endpoint = f"{_KRE_BACKEND_URL}/api/proxy/agent-chat/{_KRE_AGENT_ID}"
    try:
        import urllib.request as _req
        payload = json.dumps({"message": message, "session_id": None}).encode()
        http_req = _req.Request(
            endpoint,
            data=payload,
            headers={"Content-Type": "application/json", "User-Agent": "KRE-CloudRun-Proxy/1.0"},
            method="POST",
        )
        with _req.urlopen(http_req, timeout=60) as resp:
            body = json.loads(resp.read().decode())
            # /api/proxy/agent-chat returns {status, body, latency_ms}
            # body.response comes from chat_with_agent(); body.answer from run_agent()
            inner = body.get("body") or body
            text = None
            if isinstance(inner, dict):
                text = inner.get("response") or inner.get("answer")
            if not text:
                text = body.get("response") or body.get("answer")
            if text and isinstance(text, str) and text.strip():
                logger.info("KRE backend proxy succeeded (agent=%s)", _KRE_AGENT_ID)
                return text.strip()
    except Exception as proxy_err:
        logger.warning("KRE backend proxy failed (%s): %s", endpoint, proxy_err)
    return None


# ── Request / response models ─────────────────────────────────────────────────
class ChatRequest(BaseModel):

    message: str
    context: Optional[Dict[str, Any]] = None


class ChatResponse(BaseModel):
    response: str
    metadata: Optional[Dict[str, Any]] = None


def _looks_like_error_response(text: Optional[str]) -> bool:
    if not text:
        return True
    normalized = text.strip().lower()
    error_prefixes = (
        "error:",
        "failed",
        "exception",
        "traceback",
        "internal server error",
    )
    return normalized.startswith(error_prefixes)


# ── Endpoints ─────────────────────────────────────────────────────────────────
@app.get("/health")
async def health():
    return {
        "status": "healthy",
        "service": "validation-check",
        "agent_loaded": _agent_instance is not None,
        "agent_loading": _agent_loading,
        "kre_proxy": bool(_KRE_BACKEND_URL and _KRE_AGENT_ID),
    }


@app.post("/run")
async def run(request: ChatRequest):
    """Alias for /chat — used by the 5-endpoint contract."""
    return await chat(request)


@app.get("/info")
async def info():
    """Return agent metadata."""
    return {
        "name": "validation-check",
        "version": "1.0.0",
        "agent_loaded": _agent_instance is not None,
        "agent_loading": _agent_loading,
        "agent_load_error": _agent_load_error,
    }


@app.get("/status")
async def status():
    """Return agent operational status."""
    if _agent_loading:
        return {"status": "loading", "detail": "Agent module is still loading"}
    if _agent_instance is not None:
        return {"status": "ready", "detail": "Agent is operational"}
    if _agent_load_error:
        return {"status": "degraded", "detail": f"Agent failed to load: {_agent_load_error}"}
    return {"status": "fallback", "detail": "Using Gemini LLM fallback"}


@app.post("/upload")
async def upload_file(file: UploadFile = File(...)):
    """Upload a document to the agent's knowledge base.

    Accepts PDF, TXT, MD, CSV, and other text files.
    The file is chunked and stored in ChromaDB for RAG retrieval.
    """
    if not _rag_ready:
        raise HTTPException(status_code=503, detail="RAG store not available. Ensure chromadb is in requirements.txt.")
    try:
        file_bytes = await file.read()
        if not file_bytes:
            raise HTTPException(status_code=400, detail="Empty file")
        text = _extract_text_from_file(file_bytes, file.filename or "unknown.txt")
        if not text.strip():
            raise HTTPException(status_code=400, detail="Could not extract text from file")
        chunks_added = _ingest_to_rag(text, source=file.filename or "upload")
        total_docs = _rag_collection.count() if _rag_collection else 0
        return {
            "status": "success",
            "filename": file.filename,
            "chunks_added": chunks_added,
            "total_chunks_in_knowledge_base": total_docs,
            "message": f"Successfully ingested {chunks_added} chunks from {file.filename}",
        }
    except HTTPException:
        raise
    except Exception as exc:
        logger.error("File upload error: %s", exc)
        raise HTTPException(status_code=500, detail=str(exc))


@app.post("/chat")
async def chat(request: ChatRequest):
    """Route a chat message to the agent and return a response.

    Priority order:
      1. Local RAG context  — retrieves relevant chunks from uploaded documents
      2. KRE backend proxy  — full Firestore/RAG/MCP context
      3. Local agent module — in-container class/method invocation
      4. Vertex AI / Gemini — bare LLM with system prompt + RAG context
    """
    try:
        agent_response: Optional[str] = None

        # ── 0. Retrieve local RAG context from uploaded documents ─────────────
        local_rag_context = _query_rag(request.message, top_k=5)

        # ── 1. KRE backend proxy (has full Firestore/RAG/MCP context) ────────
        # When deployed by the KRE platform, KRE_AGENT_ID and KRE_BACKEND_URL are
        # injected as env vars. However, if we have LOCAL RAG context from
        # direct uploads, we skip the proxy and answer with local context + Gemini
        # because the KRE backend doesn't know about files uploaded directly to
        # this container.
        if not local_rag_context:
            kre_response = _call_kre_backend(request.message)
            if kre_response:
                return ChatResponse(response=kre_response)

        if _agent_instance is not None:
            # ── 1. Named methods: run / generate_response / process / execute / chat ──
            for method_name in ("run", "generate_response", "process", "execute", "chat"):
                method = getattr(_agent_instance, method_name, None)
                if not (method and callable(method)):
                    continue
                try:
                    result = method(request.message)
                    if isinstance(result, dict):
                        agent_response = (
                            result.get("response")
                            or result.get("result")
                            or result.get("answer")
                            or result.get("output")
                        )
                        if agent_response is None:
                            agent_response = str(result)
                    elif result is not None:
                        agent_response = str(result)
                    if agent_response and _looks_like_error_response(agent_response):
                        logger.warning("Agent returned error-like output via %s.%s(); using fallback", type(_agent_instance).__name__, method_name)
                        agent_response = None
                    if agent_response:
                        logger.info("Response via %s.%s()", type(_agent_instance).__name__, method_name)
                        break
                except Exception as exc:
                    logger.warning("%s.%s() failed: %s", type(_agent_instance).__name__, method_name, exc)

            # ── 2. __call__ — try multiple input formats ──────────────────────
            if not agent_response and callable(_agent_instance):
                call_formats = [
                    request.message,
                    {"message": request.message, "context": request.context},
                    {"handler": "chat", "params": {"message": request.message}},
                    {"handler": "process", "params": {"text": request.message, "query": request.message}},
                ]
                for fmt in call_formats:
                    try:
                        result = _agent_instance(fmt)
                        if isinstance(result, dict):
                            # Skip if agent returned an error for this format
                            if result.get("status") == "error" and isinstance(fmt, dict) and "handler" in fmt:
                                continue
                            agent_response = (
                                result.get("response")
                                or result.get("result")
                                or result.get("answer")
                                or result.get("output")
                            )
                            if agent_response is None:
                                agent_response = str(result)
                        elif result is not None:
                            agent_response = str(result)
                        if agent_response and _looks_like_error_response(agent_response):
                            logger.warning("Agent returned error-like output via __call__; using fallback")
                            agent_response = None
                        if agent_response:
                            logger.info("Response via __call__ (format=%s)", type(fmt).__name__)
                            break
                    except Exception as exc:
                        logger.debug("__call__ with %s failed: %s", type(fmt).__name__, exc)

        # ── 3. Fallback: real Gemini call with RAG context ─────────────────────
        if not agent_response:
            if local_rag_context:
                # Inject RAG context into the Gemini prompt so uploaded docs are used
                rag_augmented_message = (
                    f"{local_rag_context}\n\nUser question: {request.message}\n\n"
                    "Answer the user's question based on the knowledge base context above. "
                    "If the answer is in the context, provide it accurately. "
                    "If the context doesn't contain the answer, say so."
                )
                logger.info("Using Gemini fallback with %d chars of RAG context", len(local_rag_context))
                agent_response = _call_gemini_fallback(rag_augmented_message)
            else:
                logger.warning(
                    "Agent did not produce a response (loaded=%s) — using Gemini fallback",
                    _agent_instance is not None,
                )
                agent_response = _call_gemini_fallback(request.message)

        return ChatResponse(response=agent_response)

    except Exception as exc:
        logger.error("Chat handler error: %s\n%s", exc, traceback.format_exc())
        raise HTTPException(status_code=500, detail=str(exc))


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 8080))
    uvicorn.run(app, host="0.0.0.0", port=port)